---
name: Pull Request Checks
on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
jobs:
    checks:
        runs-on: ubuntu-latest
        env:
            SKIP_ENV_VALIDATION: true
        steps:
            - uses: actions/checkout@v3
            - name: Setup CI
              uses: ./.github/workflows/setup-ci
            - name: Run EsLint
              run: pnpm run lint
            - name: Run Tsc
              run: pnpm run tsc
