name: Production Release
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    release:
        types: [created]
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        environment:
            name: production
            url: https://targabay.com
        env:
            NODE_OPTIONS: "--max_old_space_size=4096"
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Update robots.txt
              run: mv public/robots.prod.txt public/robots.txt
            - name: Setup CI
              uses: ./.github/workflows/setup-ci
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --force --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
            - uses: ncipollo/release-action@v1
              with:
                  skipIfReleaseExists: true
